# Generated by Django 5.2.17 on 2026-09-25 03:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='one-time')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Class')),
            ],
        ),
    ]
