# Generated by Django 5.2.17 on 2026-09-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentrymodel',
            name='color',
            field=models.CharField(default='Black'),
        ),
        migrations.AddField(
            model_name='calendarentrymodel',
            name='which_days',
            field=models.IntegerField(default=0),
        ),
    ]
