# Generated by Django 5.2.17 on 2026-09-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalendarApp', '0002_calendarentrymodel_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarentrymodel',
            name='type',
            field=models.CharField(default='One Time'),
        ),
    ]
